plugins:
  discourse_no_likes_enabled:
    default: true
    client: false
  no_reactions_category_ids:
    default: ""
    type: category_list
  purge_phantom_likes_now:
    default: false
    type: bool
